version: "3.3"
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: backend_main
    volumes:
      - owlduty-pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  postgrest:
    image: postgrest/postgrest:v11.0.1
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: postgres://dev:dev@postgres:5432/backend_main
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_DB_SCHEMAS: v1_0
      PGRST_JWT_SECRET: thisIsAFakeJWTSecretForDevEnvOnlyAndNeverInProductionEnv
      PGRST_JWT_SECRET_IS_BASE64: "false"
    ports:
      - 33000:3000

volumes:
  owlduty-pg-data:
