[package]
name = "owlduty_domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.4.0", features = ["v4", "serde"] }
serde = { version = "1.0.164", features = ["derive"] }
